// <auto-generated />
using System;
using CryptoTrendForge.Core.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoTrendForge.Core.Migrations.Postgres
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006123159_AddBtcEntryAndCloseReason")]
    partial class AddBtcEntryAndCloseReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.BotConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("bot_configuration", (string)null);
                });

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("coins", (string)null);
                });

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.ScanNearMiss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("CandidateThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("CoinId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("Ema20ExtensionPct")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("PatternBonus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Rsi4H")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("ScoreBreakdown")
                        .HasColumnType("jsonb");

                    b.Property<int>("ScoreVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CoinId", "CreatedAt");

                    b.ToTable("scan_near_misses", (string)null);
                });

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BalancedExit")
                        .HasColumnType("numeric(18,8)");

                    b.Property<int?>("BalancedMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("BalancedReachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("BtcEntryPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("BtcTrend")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("CautiousExit")
                        .HasColumnType("numeric(18,8)");

                    b.Property<int?>("CautiousMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CautiousReachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CoinId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("EntryPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FundingRate")
                        .HasColumnType("numeric(10,6)");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketRegime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Pattern15M")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pattern1H4H")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PatternBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("RawSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reasons")
                        .HasColumnType("jsonb");

                    b.Property<string>("Risks")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ScoreBreakdown")
                        .HasColumnType("jsonb");

                    b.Property<int>("ScoreVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SignalPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("StopMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset?>("StopReachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SupportDistPct")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("SupportLevel")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("TargetsCloseReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("TargetsClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("WideExit")
                        .HasColumnType("numeric(18,8)");

                    b.Property<int?>("WideMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("WideReachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.ToTable("signals", (string)null);
                });

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.SignalOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MinutesElapsed")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAt")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("PriceChangePct")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("SignalId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SignalId", "MinutesElapsed")
                        .IsUnique();

                    b.ToTable("signal_outcomes", (string)null);
                });

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.ScanNearMiss", b =>
                {
                    b.HasOne("CryptoTrendForge.Core.Domain.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.Signal", b =>
                {
                    b.HasOne("CryptoTrendForge.Core.Domain.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("CryptoTrendForge.Core.Domain.Models.SignalOutcome", b =>
                {
                    b.HasOne("CryptoTrendForge.Core.Domain.Models.Signal", "Signal")
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });
#pragma warning restore 612, 618
        }
    }
}
